# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/composite.ui'
#
# Created: Fri Sep 14 22:05:07 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_composite(object):
    def setupUi(self, composite):
        composite.setObjectName(_fromUtf8("composite"))
        composite.resize(616, 487)
        self.centralwidget = QtGui.QWidget(composite)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.addUser = QtGui.QWidget()
        self.addUser.setObjectName(_fromUtf8("addUser"))
        self.verticalLayout = QtGui.QVBoxLayout(self.addUser)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.addUser)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.user = QtGui.QLineEdit(self.addUser)
        self.user.setEchoMode(QtGui.QLineEdit.Normal)
        self.user.setObjectName(_fromUtf8("user"))
        self.horizontalLayout_3.addWidget(self.user)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.addUser)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.secret = QtGui.QLineEdit(self.addUser)
        self.secret.setEchoMode(QtGui.QLineEdit.Password)
        self.secret.setObjectName(_fromUtf8("secret"))
        self.horizontalLayout_5.addWidget(self.secret)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.addUserButton = QtGui.QPushButton(self.addUser)
        self.addUserButton.setObjectName(_fromUtf8("addUserButton"))
        self.verticalLayout.addWidget(self.addUserButton)
        self.tabWidget.addTab(self.addUser, _fromUtf8(""))
        self.deleteUser = QtGui.QWidget()
        self.deleteUser.setObjectName(_fromUtf8("deleteUser"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.deleteUser)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.userBox = QtGui.QComboBox(self.deleteUser)
        self.userBox.setObjectName(_fromUtf8("userBox"))
        self.verticalLayout_3.addWidget(self.userBox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_2 = QtGui.QPushButton(self.deleteUser)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.deleteUser, _fromUtf8(""))
        self.viewUsers = QtGui.QWidget()
        self.viewUsers.setObjectName(_fromUtf8("viewUsers"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.viewUsers)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_6 = QtGui.QLabel(self.viewUsers)
        self.label_6.setEnabled(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.users = QtGui.QPlainTextEdit(self.viewUsers)
        self.users.setEnabled(False)
        self.users.setObjectName(_fromUtf8("users"))
        self.verticalLayout_2.addWidget(self.users)
        self.tabWidget.addTab(self.viewUsers, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        composite.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(composite)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        composite.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(composite)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        composite.setStatusBar(self.statusbar)

        self.retranslateUi(composite)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), composite.close)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), composite.wreckit)
        QtCore.QObject.connect(self.addUserButton, QtCore.SIGNAL(_fromUtf8("clicked()")), composite.addIt)
        QtCore.QObject.connect(self.secret, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.addUserButton.animateClick)
        QtCore.QObject.connect(self.user, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.addUserButton.animateClick)
        QtCore.QMetaObject.connectSlotsByName(composite)
        composite.setTabOrder(self.user, self.secret)
        composite.setTabOrder(self.secret, self.addUserButton)
        composite.setTabOrder(self.addUserButton, self.pushButton)
        composite.setTabOrder(self.pushButton, self.userBox)
        composite.setTabOrder(self.userBox, self.pushButton_2)
        composite.setTabOrder(self.pushButton_2, self.tabWidget)
        composite.setTabOrder(self.tabWidget, self.users)

    def retranslateUi(self, composite):
        composite.setWindowTitle(QtGui.QApplication.translate("composite", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("composite", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("composite", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("composite", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.addUserButton.setText(QtGui.QApplication.translate("composite", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addUser), QtGui.QApplication.translate("composite", "Add User", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("composite", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deleteUser), QtGui.QApplication.translate("composite", "Delete User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("composite", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewUsers), QtGui.QApplication.translate("composite", "View Users", None, QtGui.QApplication.UnicodeUTF8))

